timezone: America/Argentina/Buenos_Aires

year: auto

refresh_hours: 24

providers:
  f1:
    enabled: true
  f2:
    enabled: true
  f3:
    enabled: true
  wec:
    enabled: true
  elms:
    enabled: true
  mlmc:
    enabled: true
  motogp:
    enabled: true
  moto2:
    enabled: true
  moto3:
    enabled: true
  gtwc-europe:
    enabled: true
  gtwc-america:
    enabled: true
  gtwc-asia:
    enabled: true
  igtc:
    enabled: true
